"""add category_large category_medium to tasks

Revision ID: 340bd8746f87
Revises: 0001
Create Date: 2026-03-19 09:03:44.893875

"""
from alembic import op
import sqlalchemy as sa


revision = '340bd8746f87'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('category_large', sa.String(length=200), nullable=True))
    op.add_column('tasks', sa.Column('category_medium', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'category_medium')
    op.drop_column('tasks', 'category_large')
    # ### end Alembic commands ###
