"""add_multi_features

Revision ID: f1f76c14ac06
Revises: 0012
Create Date: 2026-05-02 21:49:06.812826

"""
from alembic import op
import sqlalchemy as sa


revision = 'f1f76c14ac06'
down_revision = '0012'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('notify_emails', sa.Text(), nullable=False, server_default='[]'))
    op.add_column('config', sa.Column('notify_time', sa.String(length=5), nullable=False, server_default='08:00'))
    op.add_column('config', sa.Column('notify_enabled', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('project_snapshots', sa.Column('is_baseline', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('projects', sa.Column('share_token', sa.String(length=36), nullable=True))
    op.create_index('ix_projects_share_token', 'projects', ['share_token'], unique=True)
    op.create_table('task_templates',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tasks_json', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_templates')
    op.drop_index('ix_projects_share_token', table_name='projects')
    op.drop_column('projects', 'share_token')
    op.drop_column('project_snapshots', 'is_baseline')
    op.drop_column('config', 'notify_enabled')
    op.drop_column('config', 'notify_time')
    op.drop_column('config', 'notify_emails')
    # ### end Alembic commands ###
